language: ruby
rvm:
        - 2.3
notifications:
        email: false
script: CODECLIMATE_REPO_TOKEN=3060021dfb597aeb61e254a2e49db4e7f1fb245f39b1322c23dd1dc95803de6e rails test -b
env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install: 
        - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update
        - sudo apt-get install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev language-pack-es
        - sudo locale-gen --no-archive es_CO.UTF-8
        - sudo /etc/init.d/postgresql stop
        - sudo /etc/init.d/postgresql start 9.3
        - cd test/dummy
        - psql -c 'CREATE DATABASE cor1440gen_pru;' -U postgres
        - bundle install
        - cp db/structure.sql db/structure.sql.conlock
        - cp ../../db/datos-basicas.sql db/datos-basicas.sql.conlock
        - sed -e "s/SET lock_timeout = 0;//g" db/structure.sql.conlock >db/structure.sql
        - sed -e "s/SET lock_timeout = 0;//g" db/datos-basicas.sql.conlock > ../../db/datos-basicas.sql
        - cp config/database.travis.yml config/database.yml
        - rake db:setup
        - rake sip:indices
        - cd ../..

